serenity.project.name=ZETA Testsuite
serenity.outputDirectory=target/site/serenity
serenity.requirements.dir=src/test/resources/features
serenity.test.root=features
serenity.requirement.types=UserStory,UseCase,Feature
serenity.reports=html,single-page-html,json-summary
serenity.locale=de
serenity.report.locale=de

sysinfo.Testkonzept=0.4.0
sysinfo.Testplan=0.4.0
sysinfo.Testsuite=0.4.0
sysinfo.Testproxy=0.4.0

sysinfo.testdriver=v0.4.0

sysinfo.zeta-guard-helm=0.4.0
sysinfo.authserver=0.4.0
sysinfo.pepproxy=0.4.0
