[appendix]
[#_anforderungen_mappingreferenz]
== Anforderungen (Mapping/Referenz)

Die Abdeckungsdiagramme befinden sich in Kapitel 5 (Zu testende Merkmale).

[appendix]
include::../../cucumber_methods.adoc[]

[appendix]
== Übersicht Tiger Proxy Routing

[mermaid,tiger-proxy-routing,svg]
....
include::../diagrams/Tiger-routing-diagram.mmd[]
....

Dieses Sequenzdiagramm veranschaulicht das Routing der ZETA Dienste über den Tiger Proxy.
Durch diese Routingkonfiguration werden die Anfragen zwischen allen relevanten Kommunikationsendpunkten im Tiger Proxy aufgezeichnet und können der Testsuite über einen gesonderten Management Port zugänglich gemacht werden.
Zur Auswertung werden diese aufgezeichneten Anfragen von der Testsuite heruntergeladen und in die Testauswertung integriert.

Anmerkung: Zur Verbesserung der Übersichtlichkeit wurde der Tiger Proxy in einzelne Knoten im Sequenzdiagramm aufgeteilt.
Im aktuellen Deployment existiert hingegen nur eine zentrale Tiger Proxy Instanz, über welche alle Anfragen geleitet werden.

[appendix]
== Vorlagen

include::../../../src/test/resources/features/Use_Case_Template.adoc[]

=== Testprotokoll-Vorlage

// TODO: Vorlage verlinken/einfügen

=== Fehlerbericht-Vorlage

// TODO: Vorlage verlinken/einfügen

[appendix]
include::../afos/readme.adoc[]

[appendix]
include::../testaspekte/readme.adoc[]
