[#A_25340-01]
==== A_25340-01 - ZETA Client- Zertifikatsprüfung

Der ZETA Client MUSS alle Zertifikate, die es aktiv verwendet (bspw. TLS-Verbindungsaufbau), auf Integrität und Authentizität prüfen. Falls ein Zertifikat ungültig ist, so MUSS der ZETA Client die von dem Zertifikat und den darin enthaltenen Attributen (bspw. öffentliche Schlüssel) abhängenden Arbeitsabläufe ablehnen. Der ZETA Client MUSS alle öffentlichen Schlüssel, die es verwenden will, auf eine positiv verlaufene Zertifikatsprüfung zurückführen können. Die Zertifikatsprüfung MUSS folgende Prüfungen enthalten: Der ZETA Client MUSS den Common Name (CN) oder Subject Alternative Name (SAN) des Zertifikats mit dem erwarteten Hostnamen vergleichen. Der Client MUSS die Gültigkeitsdauer des Zertifikats (Nicht vor und Nicht nach) überprüfen. Vertrauenswürdigkeit der Zertifikatskette: Sicherstellen, dass die Kette zu einer vertrauenswürdigen Root-CA führt. Revocation-Prüfung für das End-Entity-Zertifikat (Server-Zertifikat): Der Client MUSS den Widerrufsstatus prüfen. Hierbei SOLL primär eine vom Server bereitgestellte OCSP-Response (OCSP Stapling) ausgewertet werden. Fehlt diese, MUSS die Prüfung über gecachte CRLs oder OCSP-Responses erfolgen. Revocation-Prüfung für Sub-CA-Zertifikate: Der Client MUSS den Widerrufsstatus der Sub-CAs in der Kette prüfen. Um Lastspitzen und Latenzen zu vermeiden, SOLLEN hierfür vom Betriebssystem bereitgestellte Mechanismen (z. B. CRLite, lokale Trust-Stores) oder serverseitiges Multi-Stapling (TLS 1.3) verwendet werden. Falls Live-Abfragen (OCSP/CRL) für Sub-CAs notwendig sind, MÜSSEN deren Antworten zwingend entsprechend ihrer Gültigkeitsdauer (Feld nextUpdate) lokal gecacht werden. Der ZETA Client MUSS die Root-Zertifikate, die von den Mitgliedern des [CAB-Forum] ausgestellt werden, als Vertrauensanker standardmäßig unterstützen. Dies impliziert: Eine Standard-Liste von [CAB-Forum] Root-Zertifikaten ist im ZETA Client enthalten und wird regelmäßig aktualisiert oder der ZETA Client verwendet den Truststore des Betriebssystems.
