[#A_25484-01]
==== A_25484-01 - Security Monitoring - Security KPIs

ZETA Guard MUSS einmal täglich mittels dem Telemetrie-Daten-Service die folgende Sicherheits-KPIs automatisiert über die von der gematik angebotene Schnittstelle an das TI SIEM-System übermitteln:
* Anzahl versuchter Zugriffe von nicht registrierten Clients (hier muss die KPIs zwischenResource Server APIs und Clientregistrierung APIs unterscheiden)
* Anzahl von Netzwerk-Protokoll-Anomalien
* Anzahl von Zugriffen von Botnetzen
* Anzahl von Zugriffen aus jedem Land gezählt plus weitere Zugriffe, die separat in Versicherte und LE ausgewiesen werden
* Anzahl fehlerhafter Clientfreischaltungen plus weitere breakdown in Versicherte und LE
* Anzahl von Impossible travel Zugriffen (inkl.
Land- und Ortsdaten) plus weitere breakdown in Versicherte und LE
* Anzahl von Zugriffen über TOR Netzwerke plus weitere breakdown in Versicherte und LE
* Anzahl von Zugriffen über Proxies plus weitere breakdown in Versicherte und LE
* Anzahl von Zugriffen über VPNs plus weitere breakdown in Versicherte und LE
* Traffic Volumes plus weitere breakdown in Versicherte und LE
* Anzahl erkannte Angriffe in Kategorie (siehe ) plus weitere breakdown in Versicherte und LE
* Anzahl fehlerhafte Authorization Codes vom IDP.
