[#A_25669-01]
==== A_25669-01 - PEP HTTP Proxy - Zusätzliche HTTP-Header

Die Komponente HTTP Proxy MUSS die HTTP Requests mit allen HTTP-Headern an das Resource Backend weiterleiten und dabei die folgenden zusätzlichen HTTP-Header einsetzen. Tabelle #: PEP HTTP Proxy - Zusätzliche HTTP-Header HTTP-Header Format Schema Größe (max. geschätzt) zeta-user-info Base64-URL kodierte JSON Struktur des User-Info Inhalts [zeta-user-info.yaml] 250 Byte zeta-popp-token-content Base64-URL kodierte JSON Struktur des PoPP Token Inhalts. Der PoPP Header enthält das PoPP Token. Optional: Wird nur gesetzt, wenn im Request ein PoPP Header enthalten ist. PoPP Token Payload 450 Byte zeta-client-data Base64-URL kodierte JSON Struktur der Client-Daten Optional: Wird nur gesetzt, wenn die Konfiguration des HTTP Proxy für die URL des Requests die Weiterleitung der Client-Daten festlegt. [client-data.yaml] 250 Byte Gleichnamige HTTP-Header aus dem ursprünglichen HTTP-Request MÜSSEN entfernt bzw. überschrieben werden.
