[#A_26938]
==== A_26938 - ZETA/ASL-Protokoll: ZETA/ASL-Client: Prüfung der "signierten öffentlichen ZETA/ASL-Schlüssel"

Ein ZETA/ASL-Client MUSS die "signierten öffentlichen ZETA/ASL-Schlüssel" (vgl.
A_26921-*) bei der Verarbeitung von Nachricht 3 (vgl.
A_26937-*) wie folgt prüfen.
Erhält er bei einem der folgenden Prüfpunkte kein positives Prüfergebnis, so MUSS er die Verarbeitung (Handshake) abbrechen.

* Prüfung des TI-Zertifikats, das den Hashwert aus dem "cert_hash"-Datenfeld besitzt (Bezug des Zertifikats vgl.
A_26922-*), u. a. unter der Verwendung der OCSP-Response aus "ocsp_response" für die Prüfung des Sperrstatus (Prüfung ob "good").
Die OCSP-Response darf dabei nicht älter als 24 Stunden sein.
* Das ZT-Server/TI-Zertifikat MUSS zeitlich gültig sein.
Es MUSS kryptographisch in einer Zertifikats-/Signaturprüfungskette rückführbar auf eine X.509-Root-Version der TI-PKI sein.
* Das TI-Zertifikat MUSS aus der Komponenten-PKI der TI stammt (vgl.
Implementierungshinweis A_25192-*#Punkt-2) und die vom Client gewünschte Rollen-OID (bspw. "oid_epa_vau") besitzt.
* Die Signatur im "signature-ES256"-Datenfeld MUSS eine valide Signatur für die Daten im Datenfeld "signed_pub_keys" (Signaturprüfung ergibt "valid/accept") sein, unter Verwendung des öffentlichen Signatur-Schlüssels aus dem ZETA/ASL-TI-Zertifikats bei der Signaturprüfung.
* Der ECC-Schlüssel in signed_pub_keys (vgl.
Erzeugung bei A_26921-*) MUSS ein gültiger Punkt der Kurve P-256 [FIPS-186-5] sein.
Der öffentliche Schlüssel in "ML-KEM-768_PK"-Datenfeld MUSS ein gültiger ML-KEM-768-Schlüssel [FIPS-203]
sein.
* Die Zeit in "signed_pub_keys.exp" MUSS größer als die aktuelle Systemzeit (Seconds since epoch) sein, d. h. die beiden Schlüssel (ECDH_PK und ML-KEM-768_PK) sind noch zeitlich gültig.
