[#A_26921]
==== A_26921 - ZETA/ASL: ZETA/ASL-Schlüssel für die ASL-Protokoll-Schlüsselaushandlung

Ein ZETA/ASL-Server MUSS sicherstellen, dass

* es eine Signatur-Identität (AUT) aus der Komponenten-PKI der TI gibt, die technisch sichergestellt ausschließlich nur von ZETA/ASL-Instanzen verwendbar ist.
* es semi-statische Schlüsselpaare für ECDH (auf Basis Kurve P-256
[FIPS-186-5]) und ML-KEM-768 [FIPS-203] gibt, deren private Schlüssel, technisch sichergestellt, ausschließlich von ZETA/ASL-Server verwendbar sind.
* die privaten Schlüssel (aus 2.) in einer ZETA/ASL-Instanz erzeugt und verarbeitet werden,
* die semi-statischen Schlüssel eine maximale Lebensdauer von einem Monat besitzen (Hinweis: die Forward-Secrecy hängt nicht vom Wechselintervall ab, innerhalb eines Verbindungsaufbaus und der Schlüsselaushandlung dabei fließen ephemere Schlüsselwerte von Client und Server ein).
* die semi-statischen Schlüssel in einer über die Signatur-Identität authentisierten folgenden Datenstruktur aufgeführt werden.
Struktur der signierten semi-statischen öffentlichen ASL-Schlüssel ASL_Keys = {
"ECDH_PK" :
{ "crv" : "P-256", "x" : Binärwert-x-Koordinate-32-Byte-big-endian (256 Bit), "y" : Binärwert-x-Koordinate-32-Byte-big-endian (256 Bit), }, "ML-KEM-768_PK" :
Binärwert-öffentlicher-Schlüssel-nach-keygen-FIPS-203-ML-KEM-768, "iat" : Erzeugungszeits-Sekunden-Since-Epoch (integer), "exp" : Nicht-mehr-Verwendbar-nach (integer), "comment" : "Erzeugt bei ASL-Instanz xyz, Meta-Info abcd" }

 In "comment" KÖNNEN beliebige Text-Daten aufgeführt werden. Es können weitere 
Attribute hinzugeführt werden. Ein Client MUSS ihm unbekannte Attribute 
ignorieren.
 Diese Struktur wird mittels CBOR [RFC-CBOR] binär kodiert und im Folgenden 
ASL_Keys_encoded genannt.

 Diese binäre Byte-Folge wird in folgende Datenstruktur eingebracht

{
"signed_pub_keys" : ASL_Keys_encoded, "signature-ES256" : ECDSA-Signatur-SHA-256-analog-RFC-7515 (R||S => 64 Byte) binär, "cert_hash" : SHA-256-Wert des "signierenden" AUT-ASL-Zertifikats, "cdv" : Cert-Data-Version (natürliche Zahl, beginnend mit 1, vgl.
A_26922-*), "ocsp_response" :
OCSP-Response-für-das-ASL-Signaturzertifikat-nicht-älter-als-24-Stunden-DER-Kodierung }

 Diese Datenstruktur wird mittels CBOR binär kodiert (serialisiert). Das 
Ergebnis der Kodierung wird "signierte öffentliche ZETA/ASL-Schlüssel" (Plural) 
genannt.
