[#A_26924]
==== A_26924 - ZETA/ASL: ZETA/ASL-Server, Erzeugung von Fehlermeldungen

Eine ZETA/ASL-Server MUSS das Auftreten von Fehlern bei der Abarbeitung des ZETA/ASL-Protokolls wie folgt an den ZETA/ASL-Client melden.

 Als HTTP-Response-Code MUSS der ZETA/ASL-Server einen HTTP-Fehlercode (i. S. 
v. eben nicht 200) in der äußeren HTTP-Response verwenden (siehe folgende 
Tabelle). Es MUSS weiterhin eine Datenstruktur der folgenden Art erzeugen:
{
 "MessageType" : "Error",
 "ErrorCode" : ...natürliche-Zahl...,
 "ErrorMessage" : "... Menschenlesbarer Text bzw. Fehlerursache 
..."
 } 

 Diese Datenstruktur MUSS es per CBOR [RFC-CBOR] serialisieren und 
per Mime-Type "application/cbor" [RFC-CBOR] (HTTP Content-Type) im äußeren 
Response-Body aufführen.

 Ein ZETA/ASL-Server KANN weitere selbst definierte Variablen-Werte-Paare in 
der o. g. Datenstruktur aufführen.

 Folgende Fehler-Meldungen MUSS es mindestens geben: 

HTTP-Error ErrorCode ErrorMessage / Beschreibung 400 1 "Decoding Error"

 Fehler in einer Kodierung bspw. der CBOR-Kodierung 
400 2 "Missing Parameters"

 notwendige Datenfelder bspw. in der Handshake fehlen 
403 3 "GCM returns FAIL"

 Eine AES/GCM-Entschlüsselung ergibt das Symbol "FAIL". 
403 4 "PU/nonPU Failure"

403 5 "Transscript Error"

 Im Handshake wird Ungleichheit zwischen den beiden Transskript-Hashwerten 
festgestellt. 
400 6 "bad format: extended ciphertext"

 Die erste Sanity-Prüfung des erweiterten Chiffrat bspw. bei A_26928-* schlägt 
fehl. 
403 7 "is not a request"

 A_26928-* (Prüfschritt 3) 
403 8 "unknow KeyID" 
403 9 "unknown CID"
