[#A_26930]
==== A_26930 - ZETA/ASL: ZETA/ASL-Server, Response erstellen/verschlüsseln

In der ZETA/ASL-Server wird der innere HTTP-Request (Ergebnis aus A_26928-*) fachlich verarbeitet und als Antwort eine innere HTTP-Response erzeugt.
Diese ist der Klartext, der jetzt behandelt wird.

Ein ZETA/ASL-Server MUSS analog zu A_26927-* einen Header erzeugen, wobei er

* beim Response/Request-Byte den Wert 2 verwenden MUSS,
* im Request-Counter den gespeicherten Wert aus A_26928-* (Eingang des Requests) verwenden MUSS.
Die anderen Header-Variablen MÜSSEN analog zu A_26927-* festgelegt werden.
Die Konstruktion des IV MUSS analog zu A_26927-* erfolgen, nur dass für den Verschlüsselungszähler der Wert nach A_26929-* (K2_s2_app_data) verwendet werden MUSS.
Mit dem IV und dem Schlüssel K2_s2c_app_data MUSS der Klartext (s. o.) verschlüsselt werden mit AES/GCM, wobei der Header als "Additional Associated Data" bei der Verschlüsselung mit einfließt.

Das so erzeugte erweiterte Chiffrat (vgl.
A_26927-*, also Chiffrat inkl.
Header) MUSS an den Client im HTTP-Response-Body versendet werden, wobei das Aktensystem den Media-Type 'application/octet-stream' (HTTP Content-Type) verwenden MUSS.
