[#A_26940]
==== A_26940 - ZETA/ASL-Protokoll: ZETA/ASL-Server: Nachricht 4

Ein ZETA/ASL-Server MUSS bei Erhalt der Nachricht 3 das Chiffrat AEAD_ct mittels des Schlüssels K1_c2s entschlüsseln.
Schlägt dies fehl, MUSS er den Verbindungsaufbau mit einem Fehler (vgl.
A_26924-*) abbrechen.
Er MUSS analog wie der Client (vgl.
A_26937-*) die Schlüsselerzeugung der folgenden Schlüssel durchführen, nur dass er dafür die KEM-Decapsulation-Methode verwendet:

* K2_c2s_key_confirmation,
* K2_c2s_app_data,
* K2_s2c_key_confirmation,
* K2_s2c_app_data und

* KeyID (nicht vertraulich).
Er MUSS analog zu A_26937-* das Transskript des Clients und dessen SHA-256-Wert berechnen.
Er MUSS mittels K2_c2s_key_confirmation das Chiffrat "AEAD_ct_key_confirmation" aus Nachricht 3 entschlüsseln und prüfen, ob der von ihm (= ZETA/ASL-Server) berechnete Transskript-Client-Hashwert mit dem entschlüsselten Klartext übereinstimmt.
Schlägt die Entschlüsselung fehl oder wird eine Ungleichheit zwischen berechnete Transskript-Client-Hashwert und Klartext festgestellt, MUSS er den Handshake mit einem Fehler abbrechen (vgl.
A_26924-*).
Er MUSS den Transskript des ZETA/ASL-Servers als die Konketation von Nachricht1 || Nachricht 2 || Nachricht 3 berechnen, davon den SHA-256-Hashwert berechnen und diesen mittels K2_s2c_key_confirmation verschlüsseln (vgl.
A_26934-*), und erhält ein Chiffrat genannt "AEAD_ct_key_confirmation".
Er MUSS die folgende Datenstruktur erzeugen:
{
"MessageType" : "M4", "AEAD_ct_key_confirmation" : Chiffrat-AEAD_ct_key_confirmation } Diese Datenstruktur MUSS er mittels CBOR [RFC-CBOR] serialisieren.
Diese Bytefolge ist Nachricht 4.

 Er MUSS die Nachricht 4 inkl. ID (vgl. A_26935-*) an die HTTPS-Schnittstelle 
des Aktensystem übergeben. Das Aktensystem (bzw. die äußere 
HTTPS-Schnittstelle) MUSS als Antwort auf den HTTPS-Request, über den die 
Nachricht 3 eingetroffen ist, die Nachricht 4 als Antwort im Response-Body 
senden. Der zu verwendende Mime-Type MUSS "application/cbor" (HTTP 
Content-Type) für die Response sein. Im Response-Header MUSS mit der 
HTTP-Header-Variable "ZETA/ASL-CID" die ID aufgeführt werden.
